steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kubernets-407407/second_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kubernets-407407/second_app']